[package]
name = "libcore"
version.workspace = true
edition = "2021"

[dependencies]
rust-i18n = "3"
colored = "3"
downcast-rs = "2"
paste = "1"
collection_literals = "1"
derive = { path = "../derive" }
num_enum = "0.7.2"
mimalloc = "0.1"

[lib]
name = "libcore"
