[package]
name = "libcore"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-i18n = "3"
colored = "2"
downcast-rs = "1"
paste = "1"
collection_literals = "1"
derive = { path = "../derive" }

[lib]
name = "libcore"
crate-type = ["dylib"]
