[package]
name = "stdlib"
version = "0.1.0"
edition = "2021"

[dependencies]
derive = { path = "../derive" }
downcast-rs = "1"
libcore = { path = "../libcore" }
collection_literals = "1"
rust-i18n = "3"
mimalloc = "0.1"

[lib]
name = "stdlib"
crate-type = ["dylib"]
