[package]
name = "stdlib"
version.workspace = true
edition.workspace = true

[dependencies]
derive = { path = "../derive" }
downcast-rs = "2"
libcore = { path = "../libcore" }
collection_literals = "1"
rust-i18n = "3"
mimalloc = "0.1"

[lib]
name = "stdlib"
crate-type = ["dylib"]
