name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Nightly
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - name: Build
        run: cargo build
      - name: Run tests Debug
        run: cargo test
      - name: Run tests Release
        run: cargo test --release
      - name: Run miri test
        run: cargo miri test
