name: RustLinux

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Nightly
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
          export MIRIFLAGS="-Zmiri-disable-isolation"
      - name: Setting Up Valgrind
        run: |
          python3 ./script/init_valgrind_rust.py
          sudo apt update
          sudo apt install valgrind -y
      - name: Build
        run: cargo build --all
      - name: Build Release
        run: cargo build --all --release
      - name: Run tests Debug
        run: cargo test --all
      - name: Run tests Release
        run: cargo test --all --release
      # - name: Run miri test
      #   run: cargo miri test
