name: Typos

on:
  push:
    branches: ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  Typos:
    runs-on: ubuntu-latest

    steps:
      - name: typos-action
        uses: crate-ci/typos@latest
